service: csv-hero

provider:
  name: aws
  region: eu-west-1
  stage: production

plugins:
  - serverless-lift

constructs:
  webapp:
    type: static-website
    path: build
    domain: csvhero.schof.co
    certificate: arn:aws:acm:us-east-1:672895027413:certificate/ba73b576-3f22-44ce-a5be-888b3dfb72c3

resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ZGMQFFXHHTEFS
        Name: csvhero.schof.co
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: ${construct:webapp.cname}
