service: csv-hero

provider:
  name: aws
  region: eu-west-1
  stage: production

plugins:
  - serverless-lift

constructs:
  webapp:
    type: single-page-app
    path: dist
    domain: csvhero.includable.com
    certificate: arn:aws:acm:us-east-1:672895027413:certificate/a85c5a97-8afd-4137-8bc1-90d388dfa7d4
  redirect:
    type: static-website
    path: public/redirect
    domain: csvhero.schof.co
    certificate: arn:aws:acm:us-east-1:672895027413:certificate/ba73b576-3f22-44ce-a5be-888b3dfb72c3

resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ZGMQFFXHHTEFS
        Name: csvhero.schof.co
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: ${construct:redirect.cname}
    Route53RecordNew:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z05359513NAALC0BZLAAD
        Name: csvhero.includable.com
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: ${construct:webapp.cname}
